---
# vars file for minecraft - computed values, do not override
forge_installer_url: "https://maven.minecraftforge.net/net/minecraftforge/forge/{{ minecraft_version }}-{{ forge_version }}/forge-{{ minecraft_version }}-{{ forge_version }}-installer.jar"
forge_installer_jar: "forge-{{ minecraft_version }}-{{ forge_version }}-installer.jar"
forge_unix_args: "libraries/net/minecraftforge/forge/{{ minecraft_version }}-{{ forge_version }}/unix_args.txt"