---
- name: Install Java
  become: true
  apt:
    name: openjdk-17-jre-headless
    update_cache: true

- name: Set Java 17 as default
  alternatives:
    name: java
    link: /usr/bin/java
    path: /usr/lib/jvm/java-1.17.0-openjdk-amd64/bin/java
    state: present

- name: Creates minecraft backup map directory
  file:
    path: /opt/minecraft_maps
    state: directory

- name: "Check map folder is exists"
  stat:
    path: "/opt/minecraft/world"
  register: map_folder_exists

- name: "Check map folder is exists"
  debug:
    var: map_folder_exists


- name: "Backup minecraft map folder"
  when: map_folder_exists.stat.exists
  copy:
    src: "/opt/minecraft/world"
    dest: "/opt/minecraft_maps/world-{{ ansible_date_time.iso8601 }}"
    remote_src: true
    directory_mode:

- name: Delete content & directory
  file:
    state: absent
    path: /opt/minecraft

- name: "Check if path exists"
  stat:
    path: "/etc/systemd/system/minecraft.service"
  register: result

- name: Stop Minecraft Service
  when: result.stat.exists
  systemd:
    state: stopped
    name: minecraft

- name: Creates directory
  file:
    path: /opt/minecraft
    state: directory

- name: Creating a eula file
  copy:
    dest: "/opt/minecraft/eula.txt"
    content: |
      eula=true

- name: Download and extract Minecraft server
  become: true
  get_url:
    url: "https://piston-data.mojang.com/v1/objects/c9df48efed58511cdd0213c56b9013a7b5c9ac1f/server.jar"
    dest: /opt/minecraft/server.jar
    mode: "u=rwx,g=rx,o=rx"
  notify:  Start Minecraft service

- name: Create Minecraft server systemd service
  when: not result.stat.exists
  become: true
  template:
    src: minecraft.service.j2
    dest: /etc/systemd/system/minecraft.service
  notify:  Start Minecraft service
