---
- name: Install Java
  become: true
  apt:
    name: "openjdk-{{ jdk_version }}-jre-headless"
    update_cache: true

- name: "Set Java {{ jdk_version }}  as default"
  alternatives:
    name: java
    link: /usr/bin/java
    path: "/usr/lib/jvm/java-1.{{ jdk_version }}.0-openjdk-amd64/bin/java"
    state: present

- name: Creates minecraft backup map directory
  file:
    path: /opt/minecraft_maps
    state: directory

- name: "Check map folder is exists"
  stat:
    path: "/opt/minecraft/world"
  register: map_folder_exists

- name: "Check map folder is exists"
  debug:
    var: map_folder_exists


- name: "Backup minecraft map folder"
  when: map_folder_exists.stat.exists
  copy:
    src: "/opt/minecraft/world"
    dest: "/opt/minecraft_maps/world-{{ ansible_date_time.iso8601 }}"
    remote_src: true
    directory_mode:

- name: Delete content & directory
  file:
    state: absent
    path: /opt/minecraft

- name: "Check if path exists"
  stat:
    path: "/etc/systemd/system/minecraft.service"
  register: service_exists

- name: Stop Minecraft Service
  when: service_exists.stat.exists
  systemd:
    state: stopped
    name: minecraft

- name: Creates directory
  file:
    path: /opt/minecraft
    state: directory

- name: "Check map folder is exists"
  stat:
    path: "{{ path_map_folder }}"
  register: map_folder_local_exists

## Add map exists, if path for passed in ansible
- name: Copy map to server
  when: map_folder_exists.stat.exists and copy_local_map_folder == true
  copy:
    src: "{{ path_map_folder }}"
    dest: "/opt/minecraft/world"
    owner: root
    group: root
    mode: '0755'

- name: Creates mods directory
  file:
    path: /opt/minecraft/mods
    state: directory

- name: Copy mods to server
  when: copy_local_mods | bool and path_mods_folder | length > 0
  copy:
    src: "{{ path_mods_folder }}"
    dest: "/opt/minecraft/mods/"
    owner: root
    group: root
    mode: '0755'

- name: Creating a eula file
  copy:
    dest: "/opt/minecraft/eula.txt"
    content: |
      eula=true

- name: Download Forge installer
  become: true
  get_url:
    url: "{{ forge_installer_url }}"
    dest: "/opt/minecraft/{{ forge_installer_jar }}"
    mode: "u=rwx,g=rx,o=rx"

- name: Run Forge installer
  become: true
  command:
    cmd: "java -jar {{ forge_installer_jar }} --installServer"
    chdir: /opt/minecraft
    creates: /opt/minecraft/libraries
  notify: Start Minecraft service

- name: Create user_jvm_args.txt
  become: true
  copy:
    dest: "/opt/minecraft/user_jvm_args.txt"
    content: |
      -Xmx{{ minecraft_xmx }}
      -Xms{{ minecraft_xms }}

- name: Remove Forge installer
  file:
    path: "/opt/minecraft/{{ forge_installer_jar }}"
    state: absent

- name: Create Minecraft server systemd service
  become: true
  template:
    src: minecraft.service.j2
    dest: /etc/systemd/system/minecraft.service
  notify: Start Minecraft service
