dependency:
  name: galaxy

driver:
  name: docker

platforms:
  - name: minecraft
    image: ubuntu:22.04
    privileged: true
    dockerfile: roles/minecraft/molecule/default/Dockerfile
    # command: /lib/systemd/systemd status minecraft.service
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        ansible_python_interpreter: /usr/bin/python3

scenario:
  name: default
