---
dependency:
  name: galaxy

driver:
  name: docker

platforms:
  - name: minecraft
    image: ubuntu:20.04
    privileged: true
    command: systemd

provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        ansible_python_interpreter: /usr/bin/python3

scenario:
  name: default
